<a href="https://colab.research.google.com/github/Shivam-Sonawane/NLP_Lab_Work/blob/main/202321014_NLP_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install datasets
from datasets import load_dataset

dataset = load_dataset("cnn_dailymail", '1.0.0')

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})

In [ ]:
train_dataset = dataset['train']

In [ ]:
train_dataset

Dataset({
    features: ['article', 'highlights', 'id'],
    num_rows: 287113
})

In [ ]:
d = train_dataset[:10]['article']
print(d)

['LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won\'t cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don\'t plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don\'t think I\'ll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details 

In [ ]:
# Convert the list to a string
text_string = d[0]

# Print the resulting string
print(text_string)

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
doc = nlp(text_string)

In [ ]:
doc

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how

In [ ]:
for np in doc.noun_chunks:
  print(np)

LONDON
England
Reuters
Harry Potter star Daniel Radcliffe
access
a reported £20 million ($41.1 million) fortune
he
Monday
he
the money
a spell
him
Daniel Radcliffe
Harry Potter
Harry Potter
the Order
the Phoenix
the disappointment
gossip columnists
the world
the young actor
he
no plans
his cash
fast cars
drink
celebrity parties
I
those people
who
they
themselves
a massive sports car collection
something
he
an Australian interviewer
I
I
The things
I
buying
things
that
about 10 pounds
books
CDs
DVDs
Radcliffe
a casino
a drink
a pub
the horror film
"Hostel
Part II
currently six places
his number one movie
the UK box office chart
Details
he
his landmark birthday
wraps
His agent
publicist
no comment
his plans
I
some sort
party
he
an interview
none
you
it
Radcliffe's earnings
the first five Potter films
a trust fund
which
he
his growing fame
riches
the actor
he
his feet
the ground
People
kid star
the rails
he
reporters
I
it
them
His latest outing
the boy
Harry Potter
the Order
the Phoenix
re

In [ ]:
for token in doc:
  print(token.text,"====>>>>", token.pos_)

LONDON ====>>>> PROPN
, ====>>>> PUNCT
England ====>>>> PROPN
( ====>>>> PUNCT
Reuters ====>>>> PROPN
) ====>>>> PUNCT
-- ====>>>> PUNCT
Harry ====>>>> PROPN
Potter ====>>>> PROPN
star ====>>>> NOUN
Daniel ====>>>> PROPN
Radcliffe ====>>>> PROPN
gains ====>>>> VERB
access ====>>>> NOUN
to ====>>>> ADP
a ====>>>> DET
reported ====>>>> VERB
£ ====>>>> SYM
20 ====>>>> NUM
million ====>>>> NUM
( ====>>>> PUNCT
$ ====>>>> SYM
41.1 ====>>>> NUM
million ====>>>> NUM
) ====>>>> PUNCT
fortune ====>>>> NOUN
as ====>>>> SCONJ
he ====>>>> PRON
turns ====>>>> VERB
18 ====>>>> NUM
on ====>>>> ADP
Monday ====>>>> PROPN
, ====>>>> PUNCT
but ====>>>> CCONJ
he ====>>>> PRON
insists ====>>>> VERB
the ====>>>> DET
money ====>>>> NOUN
wo ====>>>> AUX
n't ====>>>> PART
cast ====>>>> VERB
a ====>>>> DET
spell ====>>>> NOUN
on ====>>>> ADP
him ====>>>> PRON
. ====>>>> PUNCT
Daniel ====>>>> PROPN
Radcliffe ====>>>> PROPN
as ====>>>> ADP
Harry ====>>>> PROPN
Potter ====>>>> PROPN
in ====>>>> ADP
" ====>>>> PUNC

In [ ]:
noun1 = ([token.lemma_ for token in doc if token.pos_ == "NOUN"])
print(noun1)

['star', 'access', 'fortune', 'money', 'spell', 'order', 'disappointment', 'gossip', 'columnist', 'world', 'actor', 'plan', 'cash', 'car', 'drink', 'celebrity', 'party', 'people', 'sport', 'car', 'collection', 'interviewer', 'month', 'thing', 'buying', 'thing', 'pound', 'book', 'cd', 'dvd', 'casino', 'drink', 'pub', 'horror', 'film', 'hostel', 'place', 'number', 'movie', 'box', 'office', 'chart', 'detail', 'birthday', 'wrap', 'agent', 'publicist', 'comment', 'plan', 'sort', 'party', 'interview', 'none', 'earning', 'film', 'trust', 'fund', 'fame', 'rich', 'actor', 'foot', 'ground', 'People', 'star', 'rail', 'reporter', 'month', 'way', 'outing', 'boy', 'order', 'record', 'side', 'role', 'film', 'review', '»', 'life', 'tv', 'movie', 'author', 'son', 'release', 'year', 'film', 'boy', 'orphanage', 'year', 'stage', 'debut', 'teenager', 'medium', 'scrutiny', 'adult', 'game', 'e', '-', 'mail', 'friend', 'copyright', 'right', 'material']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
vec = TfidfVectorizer()
tfidf_matrix = vec.fit_transform(noun1)

In [ ]:
context_matrix = tfidf_matrix.toarray()
print("NN===>>>", noun1)

NN===>>> ['star', 'access', 'fortune', 'money', 'spell', 'order', 'disappointment', 'gossip', 'columnist', 'world', 'actor', 'plan', 'cash', 'car', 'drink', 'celebrity', 'party', 'people', 'sport', 'car', 'collection', 'interviewer', 'month', 'thing', 'buying', 'thing', 'pound', 'book', 'cd', 'dvd', 'casino', 'drink', 'pub', 'horror', 'film', 'hostel', 'place', 'number', 'movie', 'box', 'office', 'chart', 'detail', 'birthday', 'wrap', 'agent', 'publicist', 'comment', 'plan', 'sort', 'party', 'interview', 'none', 'earning', 'film', 'trust', 'fund', 'fame', 'rich', 'actor', 'foot', 'ground', 'People', 'star', 'rail', 'reporter', 'month', 'way', 'outing', 'boy', 'order', 'record', 'side', 'role', 'film', 'review', '»', 'life', 'tv', 'movie', 'author', 'son', 'release', 'year', 'film', 'boy', 'orphanage', 'year', 'stage', 'debut', 'teenager', 'medium', 'scrutiny', 'adult', 'game', 'e', '-', 'mail', 'friend', 'copyright', 'right', 'material']


In [ ]:
print(context_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
context_matrix.shape

(102, 83)

In [ ]:
context_matrix.size

8466

In [ ]:
terms = vec.get_feature_names_out()
print(terms)

['access' 'actor' 'adult' 'agent' 'author' 'birthday' 'book' 'box' 'boy'
 'buying' 'car' 'cash' 'casino' 'cd' 'celebrity' 'chart' 'collection'
 'columnist' 'comment' 'copyright' 'debut' 'detail' 'disappointment'
 'drink' 'dvd' 'earning' 'fame' 'film' 'foot' 'fortune' 'friend' 'fund'
 'game' 'gossip' 'ground' 'horror' 'hostel' 'interview' 'interviewer'
 'life' 'mail' 'material' 'medium' 'money' 'month' 'movie' 'none' 'number'
 'office' 'order' 'orphanage' 'outing' 'party' 'people' 'place' 'plan'
 'pound' 'pub' 'publicist' 'rail' 'record' 'release' 'reporter' 'review'
 'rich' 'right' 'role' 'scrutiny' 'side' 'son' 'sort' 'spell' 'sport'
 'stage' 'star' 'teenager' 'thing' 'trust' 'tv' 'way' 'world' 'wrap'
 'year']


In [ ]:
noun_phrase = [chunk.text for chunk in doc.noun_chunks]
print("Noun_phrase:-", noun_phrase)


Noun_phrase:- ['LONDON', 'England', 'Reuters', 'Harry Potter star Daniel Radcliffe', 'access', 'a reported £20 million ($41.1 million) fortune', 'he', 'Monday', 'he', 'the money', 'a spell', 'him', 'Daniel Radcliffe', 'Harry Potter', 'Harry Potter', 'the Order', 'the Phoenix', 'the disappointment', 'gossip columnists', 'the world', 'the young actor', 'he', 'no plans', 'his cash', 'fast cars', 'celebrity parties', 'I', 'those people', 'who', 'they', 'themselves', 'a massive sports car collection', 'something', 'he', 'an Australian interviewer', 'I', 'I', 'The things', 'I', 'buying', 'things', 'that', 'about 10 pounds', 'books', 'CDs', 'DVDs', 'Radcliffe', 'a casino', 'a drink', 'a pub', 'the horror film', 'Hostel', 'Part II', 'currently six places', 'his number one movie', 'the UK box office chart', 'Details', 'he', 'his landmark birthday', 'wraps', 'His agent', 'publicist', 'no comment', 'his plans', 'I', 'some sort', 'party', 'he', 'an interview', 'none', 'you', 'it', "Radcliffe's ear

In [ ]:

for i in range(len(noun_phrase) - 1):
    token1 = nlp(noun_phrase[i])
    token2 = nlp(noun_phrase[i + 1])
    similarity = token1.similarity(token2)
    sim_value= (f"Similarity between '({noun_phrase[i]}' and '{noun_phrase[i + 1]})': {similarity}")
    print(sim_value)

<ipython-input-100-c8906cc95793>:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  similarity = token1.similarity(token2)


Similarity between '(LONDON' and 'England)': 0.7037405378150277
Similarity between '(England' and 'Reuters)': 0.8812214840131614
Similarity between '(Reuters' and 'Harry Potter star Daniel Radcliffe)': 0.4116709471641827
Similarity between '(Harry Potter star Daniel Radcliffe' and 'access)': 0.2689562492131817
Similarity between '(access' and 'a reported £20 million ($41.1 million) fortune)': 0.13569763158795983
Similarity between '(a reported £20 million ($41.1 million) fortune' and 'he)': 0.00461658956311607
Similarity between '(he' and 'Monday)': 0.2253098797671931
Similarity between '(Monday' and 'he)': 0.2253098797671931
Similarity between '(he' and 'the money)': 0.23754563653285934
Similarity between '(the money' and 'a spell)': 0.6597747606614132
Similarity between '(a spell' and 'him)': 0.09917850655771601
Similarity between '(him' and 'Daniel Radcliffe)': 0.26598367429455044
Similarity between '(Daniel Radcliffe' and 'Harry Potter)': 0.8922278045647166
Similarity between '(Har

In [ ]:
import pandas as pd
similarity_data=  []
similarity_data.append(sim_value)

In [ ]:
# Create a DataFrame
df_similarity = pd.DataFrame(similarity_data, columns=["Noun Phrase 1", "Noun Phrase 2", "Similarity"])

from tabulate import tabulate
print(tabulate(df_similarity, headers="keys", tablefmt="pretty", showindex=False))


# Print the DataFrame
print(df_similarity)

+------------------------------------------------+------------------------------------------------+-----------------------+
|                 Noun Phrase 1                  |                 Noun Phrase 2                  |      Similarity       |
+------------------------------------------------+------------------------------------------------+-----------------------+
|                     LONDON                     |                    England                     |  0.7037405378150277   |
|                    England                     |                    Reuters                     |  0.8812214840131614   |
|                    Reuters                     |       Harry Potter star Daniel Radcliffe       |  0.4116709471641827   |
|       Harry Potter star Daniel Radcliffe       |                     access                     |  0.2689562492131817   |
|                     access                     | a reported £20 million ($41.1 million) fortune |  0.13569763158795983  |
| a repo