In [ ]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'newspaper-text-summarization-cnn-dailymail:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F1654566%2F2734496%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240301%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240301T101757Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D16aa919fa968734bf9c2d6fd818eef4643ffd9ffceaa02ad61dbd076b3f4e9b8f03ff19c44f8e9d69bd3e4551db7631705cd43f0ef25b88f10a91fac08e11a7309e4b7cf00550a9961d538f8a293d71ec8c4a188435f2eb3df7fb24c123b7a85f3f5fa3ffc775fab0b304b8fbaee66e31ec9206fc9ed23bf8b62efbedba20603ff618d880226f7f8e1c23783f2dbb18796d0d0b2e628460dfbae35ab499c64f85939454c28609ab19eabd7b152338190a74835cf2375fab09bd52d629eb8882b36438fb4645a3a3d59275412c430f0d3cd4ce98a2ca0250709fb4419e00d530e72fe80d21187a20ef04edf5251a79b1c84d047eefb5ae6bab7bb7ccda150a9af'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')


[==================================================] 527738644 bytes downloaded
Downloaded and uncompressed: newspaper-text-summarization-cnn-dailymail
Data source import complete.


In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/newspaper-text-summarization-cnn-dailymail/cnn_dailymail/validation.csv
/kaggle/input/newspaper-text-summarization-cnn-dailymail/cnn_dailymail/test.csv
/kaggle/input/newspaper-text-summarization-cnn-dailymail/cnn_dailymail/train.csv


In [ ]:
import pandas as pd
data = pd.read_csv("/kaggle/input/newspaper-text-summarization-cnn-dailymail/cnn_dailymail/validation.csv")

In [ ]:
data.iloc[0]

id                     61df4979ac5fcc2b71be46ed6fe5a46ce7f071c3
article       Sally Forrest, an actress-dancer who graced th...
highlights    Sally Forrest, an actress-dancer who graced th...
Name: 0, dtype: object

In [ ]:
d1= data.iloc[0]["article"]
d1

"Sally Forrest, an actress-dancer who graced the silver screen throughout the '40s and '50s in MGM musicals and films such as the 1956 noir While the City Sleeps died on March 15 at her home in Beverly Hills, California. Forrest, whose birth name was Katherine Feeney, was 86 and had long battled cancer. Her publicist, Judith Goffin, announced the news Thursday. Scroll down for video . Actress: Sally Forrest was in the 1951 Ida Lupino-directed film 'Hard, Fast and Beautiful' (left) and the 1956 Fritz Lang movie 'While the City Sleeps' A San Diego native, Forrest became a protege of Hollywood trailblazer Ida Lupino, who cast her in starring roles in films including the critical and commercial success Not Wanted, Never Fear and Hard, Fast and Beautiful. Some of Forrest's other film credits included Bannerline, Son of Sinbad, and Excuse My Dust, according to her iMDB\xa0page. The page also indicates Forrest was in multiple Climax! and Rawhide television episodes. Forrest appeared as hersel

In [ ]:
import spacy


In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
doc = nlp(d1)

In [ ]:
doc

Sally Forrest, an actress-dancer who graced the silver screen throughout the '40s and '50s in MGM musicals and films such as the 1956 noir While the City Sleeps died on March 15 at her home in Beverly Hills, California. Forrest, whose birth name was Katherine Feeney, was 86 and had long battled cancer. Her publicist, Judith Goffin, announced the news Thursday. Scroll down for video . Actress: Sally Forrest was in the 1951 Ida Lupino-directed film 'Hard, Fast and Beautiful' (left) and the 1956 Fritz Lang movie 'While the City Sleeps' A San Diego native, Forrest became a protege of Hollywood trailblazer Ida Lupino, who cast her in starring roles in films including the critical and commercial success Not Wanted, Never Fear and Hard, Fast and Beautiful. Some of Forrest's other film credits included Bannerline, Son of Sinbad, and Excuse My Dust, according to her iMDB page. The page also indicates Forrest was in multiple Climax! and Rawhide television episodes. Forrest appeared as herself in

In [ ]:
for np in doc.noun_chunks:
    print(np)

Sally Forrest
an actress-dancer
who
the silver screen
the '
40s
'
50s
MGM musicals
films
the 1956 noir
the City Sleeps
March
her home
Beverly Hills
California
Forrest
whose birth name
Katherine Feeney
long battled cancer
Her publicist
Judith Goffin
the news
video
Actress
Sally Forrest
the 1951 Ida Lupino-directed film
Forrest
a protege
Hollywood trailblazer Ida Lupino
who
her
roles
films
the critical and commercial success
Fear
Some
Forrest's other film credits
Bannerline
Son
Sinbad
My Dust
her iMDB page
The page
Forrest
multiple Climax
and Rawhide television episodes
Forrest
herself
an episode
The Ed Sullivan Show
three episodes
The Dinah Shore Chevy Show
her iMDB page
She
a Broadway production
The Seven Year Itch
City News Service
other stage credits
You
It
Nanette
Damn Yankees
Forrest married writer-producer Milo Frank
He
She
her niece
Sharon Durham
nephews
Michael
Mark Feeney
Career
A San Diego native
Forrest
a protege
Hollywood trailblazer Ida Lupino
who
her
roles
films


In [ ]:
for token in doc:
    print(token.text)

Sally
Forrest
,
an
actress
-
dancer
who
graced
the
silver
screen
throughout
the
'
40s
and
'
50s
in
MGM
musicals
and
films
such
as
the
1956
noir
While
the
City
Sleeps
died
on
March
15
at
her
home
in
Beverly
Hills
,
California
.
Forrest
,
whose
birth
name
was
Katherine
Feeney
,
was
86
and
had
long
battled
cancer
.
Her
publicist
,
Judith
Goffin
,
announced
the
news
Thursday
.
Scroll
down
for
video
.
Actress
:
Sally
Forrest
was
in
the
1951
Ida
Lupino
-
directed
film
'
Hard
,
Fast
and
Beautiful
'
(
left
)
and
the
1956
Fritz
Lang
movie
'
While
the
City
Sleeps
'
A
San
Diego
native
,
Forrest
became
a
protege
of
Hollywood
trailblazer
Ida
Lupino
,
who
cast
her
in
starring
roles
in
films
including
the
critical
and
commercial
success
Not
Wanted
,
Never
Fear
and
Hard
,
Fast
and
Beautiful
.
Some
of
Forrest
's
other
film
credits
included
Bannerline
,
Son
of
Sinbad
,
and
Excuse
My
Dust
,
according
to
her
iMDB
 
page
.
The
page
also
indicates
Forrest
was
in
multiple
Climax
!
and
Rawhide
television
epis

In [ ]:
for token in doc:
    print(token.text , token.pos_)

Sally PROPN
Forrest PROPN
, PUNCT
an DET
actress NOUN
- PUNCT
dancer NOUN
who PRON
graced VERB
the DET
silver NOUN
screen NOUN
throughout ADP
the DET
' NOUN
40s NOUN
and CCONJ
' NOUN
50s NOUN
in ADP
MGM PROPN
musicals NOUN
and CCONJ
films NOUN
such ADJ
as ADP
the DET
1956 NUM
noir NOUN
While SCONJ
the DET
City PROPN
Sleeps PROPN
died VERB
on ADP
March PROPN
15 NUM
at ADP
her PRON
home NOUN
in ADP
Beverly PROPN
Hills PROPN
, PUNCT
California PROPN
. PUNCT
Forrest PROPN
, PUNCT
whose DET
birth NOUN
name NOUN
was AUX
Katherine PROPN
Feeney PROPN
, PUNCT
was AUX
86 NUM
and CCONJ
had VERB
long ADV
battled VERB
cancer NOUN
. PUNCT
Her PRON
publicist NOUN
, PUNCT
Judith PROPN
Goffin PROPN
, PUNCT
announced VERB
the DET
news NOUN
Thursday PROPN
. PUNCT
Scroll VERB
down ADP
for ADP
video NOUN
. PUNCT
Actress NOUN
: PUNCT
Sally PROPN
Forrest PROPN
was AUX
in ADP
the DET
1951 NUM
Ida PROPN
Lupino PROPN
- PUNCT
directed VERB
film NOUN
' PUNCT
Hard ADV
, PUNCT
Fast ADJ
and CCONJ
Beautiful PROPN
' P

In [ ]:
n1=([token.lemma_ for token in doc if token.pos_ == "NOUN"])
print(n1)

['actress', 'dancer', 'silver', 'screen', "'", '40', "'", '50', 'musical', 'film', 'noir', 'home', 'birth', 'name', 'cancer', 'publicist', 'news', 'video', 'actress', 'film', 'movie', 'native', 'protege', 'trailblazer', 'role', 'film', 'success', 'fear', 'film', 'credit', 'dust', 'page', 'page', 'television', 'episode', 'episode', 'episode', 'page', 'production', 'stage', 'credit', 'writer', 'producer', 'niece', 'nephew', 'career', 'native', 'protege', 'trailblazer', 'role', 'film']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vec = TfidfVectorizer()
tfidf_matrix = vec.fit_transform(n1)

In [ ]:
context_matrix = tfidf_matrix.toarray()
print("NN==>", n1)

NN==> ['actress', 'dancer', 'silver', 'screen', "'", '40', "'", '50', 'musical', 'film', 'noir', 'home', 'birth', 'name', 'cancer', 'publicist', 'news', 'video', 'actress', 'film', 'movie', 'native', 'protege', 'trailblazer', 'role', 'film', 'success', 'fear', 'film', 'credit', 'dust', 'page', 'page', 'television', 'episode', 'episode', 'episode', 'page', 'production', 'stage', 'credit', 'writer', 'producer', 'niece', 'nephew', 'career', 'native', 'protege', 'trailblazer', 'role', 'film']


In [ ]:
print(context_matrix)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
context_matrix.size

1785